# Generated by Django 3.0.6 on 2020-05-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200507_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='location',
            new_name='library',
        ),
    ]
