# Generated by Django 3.0.6 on 2020-05-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20200509_1710'),
    ]

    operations = [
    ]
